Uploading works to imgur with a valid apikey, but if upload fails it still thinks it succeeded. Also aligned my code to tabs to match

diff --git a/poomf b/poomf
--- a/poomf
+++ b/poomf
@@ -28,6 +28,9 @@ secs="0"
 ihost=pomf
 hosts="pomf uguu teknik imgur"
 
+# Insert your imgur api key here to be able to upload to imgur.
+imgurAPI=null
+
 ## FUNCTIONS
 
 depends() {
@@ -43,17 +46,17 @@ usage() {
 	poomf - puush-like functionality for pomf.se and uguu.se
 
 	Usage:
-	    $(basename "${0}") [options]
+		$(basename "${0}") [options]
 
 	Options:
-	    -d         Delay the screenshot by the specified number of seconds.
-	    -h         Show this help message.
-	    -f         Take a fullscreen screenshot.
-	    -s         Take a selection screenshot.
-	    -t         Use HTTPS, if the host supports it.
-	    -u <file>  Upload a file
-	    -w         Take a screenshot of the current window.
-        -i         Image host(pomf/uguu/teknik/imgur). If unspecified, pomf.
+		-d		 Delay the screenshot by the specified number of seconds.
+		-h		 Show this help message.
+		-f		 Take a fullscreen screenshot.
+		-s		 Take a selection screenshot.
+		-t		 Use HTTPS, if the host supports it.
+		-u <file>  Upload a file
+		-w		 Take a screenshot of the current window.
+		-i		 Image host(pomf/uguu/teknik/imgur). If unspecified, pomf.
 	HELP
 }
 
@@ -82,9 +85,9 @@ upload() {
 		echo -n "Try #${i}... "
 
 		# Upload file to selected host
-        $ihost
+		$ihost
 
-        if [ "${?}" = 0 ]; then
+		if [ "${?}" = 0 ]; then
 
 			# Copy link to clipboard
 			printf %s "${result}" | xclip -selection primary
@@ -113,42 +116,53 @@ upload() {
 }
 
 pomf() {
-    if [ "${https}" ]; then
-        result=$(curl -sf -F files[]="@${FILE}" "https://pomf.se/upload.php?output=gyazo")
-    else
-        result=$(curl -sf -F files[]="@${FILE}" "http://pomf.se/upload.php?output=gyazo")
-    fi
+	if [ "${https}" ]; then
+		result=$(curl -sf -F files[]="@${FILE}" "https://pomf.se/upload.php?output=gyazo")
+	else
+		result=$(curl -sf -F files[]="@${FILE}" "http://pomf.se/upload.php?output=gyazo")
+	fi
 }
 
 uguu() {
-    if [ "${https}" ]; then
-        echo "[${R}FAILED${N}]"
-        echo "Uguu.se doesn't support HTTPS yet."
-        exit 1
-    else
-        result=$(curl -sf -F file="@${FILE}" "http://uguu.se/api.php?d=upload")
-    fi
+	if [ "${https}" ]; then
+		echo "[${R}FAILED${N}]"
+		echo "Uguu.se doesn't support HTTPS yet."
+		exit 1
+	else
+		result=$(curl -sf -F file="@${FILE}" "http://uguu.se/api.php?d=upload")
+	fi
 }
 
 teknik() {
-    if [ "${https}" ]; then
-        result=$(curl -sf -F file="@${FILE}" https://api.teknik.io/upload/post)
-    else
-        echo "[${R}FAILED${N}]"
-        echo "teknik.io uploading must be done with HTTPS(-t flag)"
-        exit 1
-    fi
+	if [ "${https}" ]; then
+		result=$(curl -sf -F file="@${FILE}" https://api.teknik.io/upload/post)
+	else
+		echo "[${R}FAILED${N}]"
+		echo "teknik.io uploading must be done with HTTPS(-t flag)"
+		exit 1
+	fi
 
-    if [[ ! "${result}" =~ "error" ]]; then
-        result="${result##*name\":\"}"
-        result="${result%%\"*}"
-        result="https://u.teknik.io/${result}"
-    fi
+	if [[ ! "${result}" =~ "error" ]]; then
+		result="${result##*name\":\"}"
+		result="${result%%\"*}"
+		result="https://u.teknik.io/${result}"
+	fi
 }
 
-#imgur() {
+imgur() {
+	if [ "${https}" ]; then
+		echo "[${R}FAILED${N}]"
+		echo "imgur uploading must be done with HTTP(no -t flag)"
+		exit 1
+	else
+		result=$(curl -sf -F "key=$imgurAPI" -H "Expect: " -F "image=@${FILE}" \
+			http://imgur.com/api/upload.xml )
+	fi
 
-#}
+	if [ "${?}" = 0 ]; then
+		result=$(echo $result | sed -r 's/.*<original_image>(.*)<\/original_image>.*/\1/')
+	fi
+}
 
 ## EXIT IF NO ARGUMENTS FOUND
 if [ $# -lt 1 ]; then
@@ -174,13 +188,13 @@ while getopts :d:fghstui:w opt; do
 		u)
 			# Change $FILE to the specified file with -u
 			upl=true
-                        FILE="${OPTARG}" ;;
+						FILE="${OPTARG}" ;;
 		w)
 			# Take shot of current window.
-                        win=true ;;
-        i)
-            #Set host
-            [[ "$hosts" =~ "${OPTARG}" ]] && ihost=${OPTARG} || exit 1 ;;
+						win=true ;;
+		i)
+			#Set host
+			[[ "$hosts" =~ "${OPTARG}" ]] && ihost=${OPTARG} || exit 1 ;;
 		h)
 			# Show help and exit with EXIT_SUCCESS
 			usage
