Style fixes.

diff --git a/poomf b/poomf
--- a/poomf
+++ b/poomf
@@ -1,191 +1,183 @@
 #!/usr/bin/env bash
 #
-# poomf - command-line uploader for pomf.se, uguu.se, and teknik.io
-# by joe - js1 at openmailbox dot org
-# refactored by arianon - arianon at openmailbox dot org
+# poomf - upload to pomf.se, uguu.se, and teknik.io
 #
 
 ## CONFIGURATION
 
-# Colors
-N=$(tput sgr0)
-R=$(tput setaf 1)
-G=$(tput setaf 2)
+# colors
+n="$(tput sgr0)"
+r="$(tput setaf 1)"
+g="$(tput setaf 2)"
 
-# Screenshot utility
-fshot="maim --hidecursor"
-sshot="maim -s --hidecursor"
+# screenshot utility
+fshot='maim --hidecursor'
+sshot='maim -s --hidecursor'
 wshot="maim -i $(xprop -root _NET_ACTIVE_WINDOW | grep -o '0x.*') --hidecursor"
 
-# Default screenshot name
-FILE=$(mktemp --suffix=.png)
+# default screenshot name
+FILE="$(mktemp --suffix=.png)"
 
-# Default delay
-secs="0"
+# default delay
+secs='0'
 
-# Image host
-usehost="pomf"
-hosts="pomf uguu teknik"
+# image host
+usehost='pomf'
+hosts='pomf uguu teknik'
+
+## EXIT IF NO ARGUMENTS ARE FOUND
+
+if [ $# -lt 1 ]; then
+  echo '`poomf` requres and argument. Run `poomf -h` for help.'
+  exit 1
+fi
 
 ## FUNCTIONS
 
 depends() {
-	if ! type curl &> /dev/null; then
-		echo >&2 "Checking for curl... [${R}FAILED${N}]"
-		echo "\`curl\` not found."
-		exit 1
-	fi
+  if ! type curl &> /dev/null; then
+    echo >&2 "Checking for curl... [${r}FAILED${n}]"
+    echo '`curl` not found.'
+    exit 1
+  fi
 }
 
 usage() {
-	cat <<-HELP
-	poomf - puush-like functionality for pomf.se, uguu.se, and teknik.io
+  cat <<-HELP
+poomf - upload to pomf.se, uguu.se, and teknik.io
 
-	Usage:
-		$(basename "${0}") [options]
+Usage:
+  $(basename "${0}") [options]
 
-	Options:
-	    -d		   Delay the screenshot by the specified number of seconds.
-	    -f		   Take a fullscreen screenshot.
-	    -h		   Show this help message.
-	    -o		   Select a host to use. Can be pomf, uguu, or teknik.
-	    -s		   Take a selection screenshot.
-	    -t		   Use HTTPS, if the host supports it.
-	    -u <file>	   Upload a file.
-	    -x		   Do not notify dbus, update the log, or modify the clipboard.
-	    -w		   Take a screenshot of the current window.
-	HELP
+Options:
+    -d           Delay the screenshot by the specified number of seconds.
+    -f           Take a fullscreen screenshot.
+    -h           Show this help message.
+    -o           Select a host to use. Can be pomf, uguu, or teknik.
+    -s           Take a selection screenshot.
+    -t           Use HTTPS, if the host supports it.
+    -u <file>    Upload a file.
+    -x           Do not notify dbus, update the log, or modify the clipboard.
+    -w           Take a screenshot of the current window.
+HELP
 }
 
 delay() {
-	for (( i=secs; i > 0; --i )) ; do
-		echo "$i..."
-		sleep 1
-	done
+  for (( i=secs; i > 0; --i )) ; do
+    echo "${i}..."
+    sleep 1
+  done
 }
 
 screenshot() {
-	if [ "${ful}" ]; then
-		# Take fullscreen shot
-		${fshot} "${FILE}"
-	elif [ "${sel}" ]; then
-		# Take selection shot
-		${sshot} "${FILE}"
-	elif [ "${win}" ]; then
-		# Take window shot
-		${wshot} "${FILE}"
-	fi
+  if [ "${ful}" ]; then
+    ${fshot} "${FILE}"
+  elif [ "${sel}" ]; then
+    ${sshot} "${FILE}"
+  elif [ "${win}" ]; then
+    ${wshot} "${FILE}"
+  fi
 }
 
 upload() {
-	for (( i = 1; i <= 3; i++ )); do
-		printf %s "Try #${i}... "
+  for (( i = 1; i <= 3; i++ )); do
+    printf %s "Try #${i}... "
 
-		# Upload file to selected host
-		if [ "${https}" ]; then
-			case "${usehost}" in
-				pomf) upurl="https://pomf.se/upload.php?output=gyazo" ;;
-				teknik) upurl="https://api.teknik.io/upload/post" ;;
-				uguu) upurl="unsupported" ;;
-			esac
-		else
-			case "${usehost}" in
-				pomf) upurl="http://pomf.se/upload.php?output=gyazo" ;;
-				teknik) upurl="unsupported" ;;
-				uguu) upurl="http://uguu.se/api.php?d=upload" ;;
-			esac
-		fi
+    if [ "${https}" ]; then
+      case "${usehost}" in
+        pomf) upurl='https://pomf.se/upload.php?output=gyazo' ;;
+        teknik) upurl='https://api.teknik.io/upload/post' ;;
+        uguu) upurl='unsupported' ;;
+      esac
+    else
+      case "${usehost}" in
+        pomf) upurl='http://pomf.se/upload.php?output=gyazo' ;;
+        teknik) upurl='unsupported' ;;
+        uguu) upurl='http://uguu.se/api.php?d=upload' ;;
+      esac
+    fi
 
-		if [ "${upurl}" = "unsupported" ]; then
-			echo "[${R}FAILED${N}]"
-			echo "${usehost} doesn't support $([ "${https}" ] && echo HTTPS || echo HTTP)."
-			exit 1
-		else
-			if [ "${usehost}" = "pomf" ]; then
-				result=$(curl -sf -F files[]="@${FILE}" "${upurl}")
-			elif [ "${usehost}" = "uguu" ]; then
-				result=$(curl -sf -F file="@${FILE}" "${upurl}")
-			elif [ "${usehost}" = "teknik" ]; then
-				result=$(curl -sf -F file="@${FILE}" "${upurl}")
-				result="${result##*name\":\"}"
-				result="${result%%\"*}"
-				result="https://u.teknik.io/${result}"
-			fi
-		fi
+    if [ "${upurl}" = 'unsupported' ]; then
+      echo "[${r}FAILED${n}]"
+      echo "${usehost} doesn't support $([ "${https}" ] && echo HTTPS || echo HTTP)."
+      exit 1
+    else
+      if [ "${usehost}" = 'pomf' ]; then
+        result="$(curl -sf -F files[]="@${FILE}" "${upurl}")"
+      elif [ "${usehost}" = 'uguu' ]; then
+        result="$(curl -sf -F file="@${FILE}" "${upurl}")"
+      elif [ "${usehost}" = 'teknik' ]; then
+        result="$(curl -sf -F file="@${FILE}" "${upurl}")"
+        result="${result##*name\":\"}"
+        result="${result%%\"*}"
+        result="https://u.teknik.io/${result}"
+      fi
+    fi
 
-		if [ "${?}" = 0 ]; then
+    if [ "${?}" = 0 ]; then
 
-			if [ ! "${nocomm}" ]; then 
-				# Copy link to clipboard
-				printf %s "${result}" | xclip -selection primary
-				printf %s "${result}" | xclip -selection clipboard
+      if [ ! "${nocomm}" ]; then
+        printf %s "${result}" | xclip -selection primary
+        printf %s "${result}" | xclip -selection clipboard
 
-				# Log url to file
-				echo "$(date +"%D %R") | "${FILE}" | ${result}" >> ~/.pomfs.txt
+        echo "$(date +"%D %R") | "${FILE}" | "${result}"" >> ~/.pomfs.txt
 
-				# Notify user of completion
-				notify-send "pomf!" "${result}"
-			fi
+        notify-send 'pomf!' "${result}"
+      fi
 
-			# Output message to term
-			echo "[${G}OK${N}]"
-			echo "File has been uploaded: ${result}"
+      echo "[${g}OK${n}]"
+      echo "File has been uploaded: ${result}"
 
-			# If we took a screenshot, remove the temporary file
-			if [ -z "${upl}" ]; then
-				rm "${FILE}"
-			fi
+      # if we took a screenshot, remove the temporary file
+      if [ -z "${upl}" ]; then
+        rm "${FILE}"
+      fi
 
-			exit
-		else
-			echo "[${R}FAILED${N}]"
-		fi
-	done
+      exit
+    else
+      echo "[${r}FAILED${n}]"
+    fi
+  done
 }
 
-## EXIT IF NO ARGUMENTS FOUND
-if [ $# -lt 1 ]; then
-	usage
-	exit 1
-fi
-
 ## PARSE OPTIONS
+
 while getopts :d:fho:stu:wx opt; do
-	case "${opt}" in
-		d)
-			# Set delay value
-			secs="${OPTARG}" ;;
-		f)
-			# Fullscreen
-			ful=true ;;
-		h)
-			# Print help
-			usage
-			exit 0 ;;
-		o)
-			# Set host
-			[[ "${hosts}" =~ ${OPTARG} ]] && usehost=${OPTARG} || exit 1 ;;
-		s)
-			# Take shot with selection
-			sel=true ;;
-		t)
-			# Use HTTPS
-			https=true ;;
-		u)
-			# Change $FILE to the specified file with -u
-			upl=true
-			FILE="${OPTARG}" ;;
-		w)
-			# Take shot of current window
-			win=true ;;
-		x)
-			# Do not notify dbus, update log, or modify clipboard
-			nocomm=true ;;
-		*)
-			# Print help and EXIT_FAILURE
-			usage
-			exit 1 ;;
-	esac
+  case "${opt}" in
+    d)
+      # set delay value
+      secs="${OPTARG}" ;;
+    f)
+      # fullscreen
+      ful='true' ;;
+    h)
+      # print help
+      usage
+      exit 0 ;;
+    o)
+      # set host
+      [[ "${hosts}" =~ ${OPTARG} ]] && usehost="${OPTARG}" || exit 1 ;;
+    s)
+      # take shot with selection
+      sel='true' ;;
+    t)
+      # use https
+      https='true' ;;
+    u)
+      # change $FILE to the specified file with -u
+      upl='true'
+      FILE="${OPTARG}" ;;
+    w)
+      # take shot of current window
+      win='true' ;;
+    x)
+      # do not notify dbus, update log, or modify clipboard
+      nocomm='true' ;;
+    *)
+      # print help and EXIT_FAILURE
+      usage
+      exit 1 ;;
+  esac
 done
 
 ## EXECUTE FUNCTIONS
@@ -196,4 +188,4 @@ screenshot
 upload
 
 # If the program doesn't exit at the for-loop, the upload failed.
-echo "File was not uploaded, did you specify a valid filename?"
+echo 'File was not uploaded, did you specify a valid filename?'
